# api/login route configuration
api_login:
    path: /api/login
    methods: ['POST']

# Load controllers with attributes
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
